name: voolo_app
description: Voolo Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  shared_preferences: ^2.0.15
  wave: ^0.2.2
  fluttertoast: ^8.0.9
  flutter_easyloading: ^3.0.5
  flutter_svg: ^1.1.6
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/app_icon.png"